services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  api:
    build: .
    image: trafficflow:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CALLBACK_HOST=http://api:8000
      - AI_LOCAL=true
      - AI_ENABLE_STABILIZATION=false
      - AI_MODEL_PATH=models/yolo11m.pt
      - AI_CLASS_IDS=2,3,5,7
      - AI_CLASS_NAME_MAP=
      - AI_IMGSZ=960
      - ROI_MODE=full_frame
      - CELERY_QUEUE_NAME=trafficflow_gpu_queue
      - YTDLP_COOKIES_FILE=/run/secrets/youtube_cookies.txt
      - YTDLP_JS_RUNTIME=node
      - YTDLP_REMOTE_COMPONENTS=ejs:github
    volumes:
      - C:/Users/ADMIN/Downloads/cookies.txt:/run/secrets/youtube_cookies.txt:ro
    depends_on:
      redis:
        condition: service_healthy
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  worker:
    build: .
    image: trafficflow:latest
    command: celery -A worker.celery_app worker --pool=prefork --concurrency=1 -Q trafficflow_gpu_queue --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CALLBACK_HOST=http://api:8000
      - AI_LOCAL=true
      - AI_ENABLE_STABILIZATION=false
      - AI_MODEL_PATH=models/yolo11m.pt
      - AI_CLASS_IDS=2,3,5,7
      - AI_CLASS_NAME_MAP=
      - AI_IMGSZ=960
      - ROI_MODE=full_frame
      - CELERY_QUEUE_NAME=trafficflow_gpu_queue
    depends_on:
      redis:
        condition: service_healthy
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
